import './globals.css'
import type { Metadata } from 'next'
import { Nanum_Gothic } from 'next/font/google'
import Header from "@/components/Header";
import Footer from "@/components/Footer";

const gothic = Nanum_Gothic({
  subsets: ['latin'],
  weight: '400'
})

export const metadata: Metadata = {
  title: 'Feth\'s blog',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="ko" className={gothic.className}>
      <body className={'relative '}>
        <Header/>
        <div className={'h-16'}/>
        <main className={'w-full h-full'}>
          {children}
        </main>
        <Footer />
      </body>
    </html>
  )
}
