import './globals.css'
import type { Metadata } from 'next'
import Header from "@/components/Header";
import Footer from "@/components/Footer";

export const metadata: Metadata = {
  title: 'Feth\'s blog',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="ko" >
      <body className={'relative'}>
        <Header/>
        {/* header fixed 높이 */}
        <div className={`h-16`}/>
        <main className={'flex items-center justify-center p-4'}>
          <div className={'container'}>
          {children}
          </div>
        </main>
        <Footer />
      </body>
    </html>
  )
}
